server:
  port: 8001
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
zuul:
  routes:
    nacoslean-core:
      path: /**
      serviceId: nacoslean-core
      sensitive-headers:

nacoslean-core:
  ribbon:
    ReadTimeout: 60000  # 单位毫秒数
    SocketTimeout: 60000